-- liquibase formated sql
-- changeset norekhov:1
CREATE TABLE users
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    phone      VARCHAR(255) NOT NULL UNIQUE,
    avatar     VARCHAR(255),
    enabled    integer default 1 NOT NULL
);

CREATE TABLE ad
(
    pk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    ad_text     TEXT         NOT NULL,
    price       INT          NOT NULL,
    user_id     INT REFERENCES users (id),
    image_url   VARCHAR(255)
);
CREATE TABLE comment
(
    pk  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      TEXT   NOT NULL,
    created_at BIGINT NOT NULL,
    user_id   INT REFERENCES users (id),
    ad_id     INT REFERENCES ad (pk)
);